### ISSUE TITLE
NPE in check_suites

### ISSUE THREAD

**Issue by nineinchnick** [nineinchnick/trino-rest#155]
```
java.lang.NullPointerException: at index 4
	at com.google.common.collect.ObjectArrays.checkElementNotNull(ObjectArrays.java:229)
	at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:219)
	at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:213)
	at com.google.common.collect.ImmutableList.construct(ImmutableList.java:353)
	at com.google.common.collect.ImmutableList.of(ImmutableList.java:225)
	at pl.net.was.rest.github.model.CheckSuite.toRow(CheckSuite.java:124)
	at pl.net.was.rest.github.GithubRest.lambda$getCheckSuites$43(GithubRest.java:1884)
```

**Comment by nineinchnick** [comment]
Most probably done already.
